/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gravicor;

import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import org.apache.commons.codec.digest.DigestUtils;

/**
 *
 * @author Daniel
 */
public class EditarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form AnadirUsuario
     */
    
    private String idUsuario = "1";
    
    public void setIdUsuario(String usuario){
        this.idUsuario = usuario;
    }
    
    public void iniciarPantalla(){
        String query = "select * from usuario where usuario.IDUSUARIO = " + idUsuario;
        String[] Columnas = {"IDUSUARIO" ,"EMAIL", "CONTRASENA", "NOMBRES", "APELLIDOS", "GESTIONPIEDRAGRENA", "GESTIONVENTAS","REPORTES","COBRANZA","TESORERIA","GESTIONGASTOSGENERALES","CONFIGURACIONCUENTAS","ACTIVO","USERNAME"};
        
        try{
            LinkedList<LinkedList<String>> resultado = Globales.baseDatos.select(query, Columnas);
            if(resultado == null){
                throw new NoConectionDataBaseException("No fue posible conectarse a la base de datos");
            }
            contrasenaT.setEnabled(false);
            rContrasenaT.setEnabled(false);
            //System.out.println(resultado);
            emailT.setText(resultado.get(1).get(0));
            //contrasenaT.setText(resultado.get(2).get(0));
            //rContrasenaT.setText(resultado.get(2).get(0));
            nombresT.setText(resultado.get(3).get(0));
            apellidosT.setText(resultado.get(4).get(0));
            usuarioT.setText(resultado.get(13).get(0));
            usuarioT.setEnabled(false);
            
            JRadioButton[] botones = {piedraB, ventasB, reportesB, cobranzaB, tesoreriaB, gastosB, cuentasB};
            for(int i = 0; i<botones.length; i++){
                String r = resultado.get(i+5).get(0);
                if(r.equals(new String("0"))){
                    botones[i].setSelected(false);
                }
                else{
                    botones[i].setSelected(true);
                }
                
            }
            if(resultado.get(12).get(0).equals(new String("1"))){
                activoCB.setSelected(true);
            }
            else{
                activoCB.setSelected(false);
            }
            if(activoCB.isSelected()){
                //JRadioButton[] botones = {piedraB, ventasB, reportesB, cobranzaB, tesoreriaB, gastosB, cuentasB};
                for(int i= 0; i< botones.length; i++){
                    botones[i].setEnabled(true);
                }
                permisosL.setEnabled(true);
            }
            else{
                //JRadioButton[] botones = {piedraB, ventasB, reportesB, cobranzaB, tesoreriaB, gastosB, cuentasB};
                for(int i= 0; i< botones.length; i++){
                    botones[i].setEnabled(false);
                }
                permisosL.setEnabled(false);

            }
        }
        catch(NoConectionDataBaseException e){
            JOptionPane.showMessageDialog(this, e.getMessage() ,"Error de conexión",  JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public EditarUsuario() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("Añadir Usuario");
        activoCB.setSelected(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        emailT = new javax.swing.JTextField();
        nombresT = new javax.swing.JTextField();
        apellidosT = new javax.swing.JTextField();
        contrasenaT = new javax.swing.JPasswordField();
        rContrasenaT = new javax.swing.JPasswordField();
        activoCB = new javax.swing.JCheckBox();
        piedraB = new javax.swing.JRadioButton();
        permisosL = new javax.swing.JLabel();
        ventasB = new javax.swing.JRadioButton();
        reportesB = new javax.swing.JRadioButton();
        cobranzaB = new javax.swing.JRadioButton();
        cuentasB = new javax.swing.JRadioButton();
        gastosB = new javax.swing.JRadioButton();
        tesoreriaB = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        usuarioT = new javax.swing.JTextField();
        editarContrasenaCB = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(249, 255, 255));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gravicor/AssetsNuevos/aceptar.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Gravicor/AssetsNuevos/aceptar2.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel1.setText("Email:");

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel2.setText("Contraseña:");

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel3.setText("Repite contraseña:");

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel4.setText("Nombres:");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel5.setText("Apellidos:");

        emailT.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        nombresT.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        apellidosT.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        contrasenaT.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        rContrasenaT.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        activoCB.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        activoCB.setText("Usuario Activo");
        activoCB.setContentAreaFilled(false);
        activoCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activoCBActionPerformed(evt);
            }
        });

        piedraB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        piedraB.setText("Gestión de piedra en greña");
        piedraB.setContentAreaFilled(false);
        piedraB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                piedraBActionPerformed(evt);
            }
        });

        permisosL.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        permisosL.setText("Permisos:");

        ventasB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ventasB.setText("Gestión de ventas");
        ventasB.setToolTipText("");
        ventasB.setContentAreaFilled(false);
        ventasB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventasBActionPerformed(evt);
            }
        });

        reportesB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        reportesB.setText("Reportes y estadistícas");
        reportesB.setContentAreaFilled(false);

        cobranzaB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cobranzaB.setText("Cobranza");
        cobranzaB.setContentAreaFilled(false);

        cuentasB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cuentasB.setText("Configuración de cuentas");
        cuentasB.setContentAreaFilled(false);

        gastosB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        gastosB.setText("Gestión de gastos");
        gastosB.setContentAreaFilled(false);

        tesoreriaB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tesoreriaB.setText("Inventarios");
        tesoreriaB.setContentAreaFilled(false);
        tesoreriaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tesoreriaBActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gravicor/AssetsNuevos/cancelar.png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Gravicor/AssetsNuevos/cancelar2.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        jLabel7.setText("Editar usuario");

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel6.setText("Usuario:");

        usuarioT.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        usuarioT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioTActionPerformed(evt);
            }
        });

        editarContrasenaCB.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        editarContrasenaCB.setText("¿Cambiar contraseña?");
        editarContrasenaCB.setOpaque(false);
        editarContrasenaCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarContrasenaCBActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gravicor/AssetsNuevos/encabezadoLogoGravicor.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(287, 287, 287)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(permisosL))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ventasB)
                                    .addComponent(piedraB)
                                    .addComponent(cobranzaB)
                                    .addComponent(reportesB))
                                .addGap(99, 99, 99)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(gastosB)
                                    .addComponent(tesoreriaB)
                                    .addComponent(cuentasB)))
                            .addComponent(activoCB, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(editarContrasenaCB))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel6)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel2)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel1))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(76, 76, 76)
                                                .addComponent(jLabel5))))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(apellidosT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
                                        .addComponent(nombresT, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rContrasenaT, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(contrasenaT, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(emailT, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(usuarioT)))))))
                .addGap(0, 124, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(emailT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(editarContrasenaCB)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contrasenaT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rContrasenaT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombresT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellidosT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(usuarioT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(activoCB)
                .addGap(18, 18, 18)
                .addComponent(permisosL)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(piedraB)
                    .addComponent(tesoreriaB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ventasB)
                    .addComponent(gastosB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reportesB)
                    .addComponent(cuentasB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cobranzaB)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void piedraBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_piedraBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_piedraBActionPerformed

    private void ventasBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventasBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ventasBActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        boolean bandera = Globales.baseDatos.conectarBD(Globales.baseDatos.generarURL());
        if(bandera != false){
            ConfiguracionCuentas cuentas = new ConfiguracionCuentas();
            cuentas.setVisible(true);
            this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(this, "Error al conectarse a la base de datos: " + Globales.baseDatos.getUltimoError(), "Error de conexión con la base de datos", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
            if(!Globales.isValidEmailAddress(emailT.getText()) || emailT.getText().length()>50){
                throw new NoTypeRequiredException("El e-mail no tiene una direccion valida");
            }
            if(editarContrasenaCB.isSelected() && (contrasenaT.getPassword().length< 6 || contrasenaT.getPassword().length> 50)){
                throw new NoTypeRequiredException("La contraseña es muy corta. Por lo menos debes usar 6 caracteres y máximo 50 caracteres");
            }
            String original = new String(contrasenaT.getPassword());
            String repeticion = new String(rContrasenaT.getPassword());
            if(editarContrasenaCB.isSelected() && (!original.equals(repeticion))){
                throw new NoTypeRequiredException("Las contraseñas no coinciden, por favor verifícalas");
            }
            if(nombresT.getText().length()<4 || nombresT.getText().length()>50){
                throw new NoTypeRequiredException("Existe un error en el formato del campo 'nombres', por favor corrígelo");
            }
            if(apellidosT.getText().length()<4 || apellidosT.getText().length()>50){
                throw new NoTypeRequiredException("Existe un error en el formato del campo 'apellidos', por favor corrígelo");
            }
            
            original=DigestUtils.md5Hex(original); 
            JRadioButton[] botones = {piedraB, ventasB, reportesB, cobranzaB, tesoreriaB, gastosB, cuentasB};
            String[] l = new String[8];
            for(int i = 0; i<botones.length; i++){
                if(botones[i].isSelected()){
                    l[i] ="1" ;
                }
                else{
                    l[i] = "0";
                }
            }
            if(activoCB.isSelected()){
                l[7] = "1";
            }
            else{
                l[7] = "2";
            }
            String query = "";
            if(editarContrasenaCB.isSelected()){
                String[] u = {"EMAIL = '"+ emailT.getText().toLowerCase()+"'," ,
                "CONTRASENA = '" + original + "',", 
                "NOMBRES = '" + nombresT.getText().toLowerCase()+ "',", 
                "APELLIDOS = '" + apellidosT.getText().toLowerCase()+"',", 
                "GESTIONPIEDRAGRENA = "+l[0] + ",", 
                "GESTIONVENTAS = "+ l[1]+ ",",
                "REPORTES = "+ l[2]+ ",",
                "COBRANZA = "+l[3] + ",",
                "TESORERIA = "+ l[4]+ ",",
                "GESTIONGASTOSGENERALES = "+ l[5]+ ",",
                "CONFIGURACIONCUENTAS = "+ l[6]+ ",",
                "ACTIVO = "+ l[7]};



                 query = "update usuario set " + u[0] + u[1] + u[2] + u[3] + u[4] + u[5] + u[6] + u[7] + u[8] + u[9] + u[10] + u[11] + " where usuario.IDUSUARIO = " + idUsuario;
                //System.out.println(query);
            }
            else{
                String[] u = {"EMAIL = '"+ emailT.getText().toLowerCase()+"'," ,
                " ", 
                "NOMBRES = '" + nombresT.getText().toLowerCase()+ "',", 
                "APELLIDOS = '" + apellidosT.getText().toLowerCase()+"',", 
                "GESTIONPIEDRAGRENA = "+l[0] + ",", 
                "GESTIONVENTAS = "+ l[1]+ ",",
                "REPORTES = "+ l[2]+ ",",
                "COBRANZA = "+l[3] + ",",
                "TESORERIA = "+ l[4]+ ",",
                "GESTIONGASTOSGENERALES = "+ l[5]+ ",",
                "CONFIGURACIONCUENTAS = "+ l[6]+ ",",
                "ACTIVO = "+ l[7]};



                 query = "update usuario set " + u[0] + u[1] + u[2] + u[3] + u[4] + u[5] + u[6] + u[7] + u[8] + u[9] + u[10] + u[11] + " where usuario.IDUSUARIO = " + idUsuario;
                //System.out.println(query);
            }
            boolean res = Globales.baseDatos.update(query);//Globales.bdTemp.insert(query);
            if(res){
                
                ConfiguracionCuentas cuentas = new ConfiguracionCuentas();
                cuentas.setVisible(true);
                this.dispose();
            }
            else{
                throw new NoConectionDataBaseException("Error al conectar con la base de datos: " + Globales.baseDatos.getUltimoError());
            }
        }
        catch(NoTypeRequiredException e){
            JOptionPane.showMessageDialog(this, e.getMessage() ,"Error de formato",  JOptionPane.ERROR_MESSAGE);
        } catch (NoConectionDataBaseException e) {
            JOptionPane.showMessageDialog(this, e.getMessage() ,"Error de conexión",  JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void activoCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activoCBActionPerformed
        if(activoCB.isSelected()){
            JRadioButton[] botones = {piedraB, ventasB, reportesB, cobranzaB, tesoreriaB, gastosB, cuentasB};
            for(int i= 0; i< botones.length; i++){
                botones[i].setEnabled(true);
            }
            permisosL.setEnabled(true);
        }
        else{
            JRadioButton[] botones = {piedraB, ventasB, reportesB, cobranzaB, tesoreriaB, gastosB, cuentasB};
            for(int i= 0; i< botones.length; i++){
                botones[i].setEnabled(false);
            }
            permisosL.setEnabled(false);
            
        }
    }//GEN-LAST:event_activoCBActionPerformed

    private void usuarioTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioTActionPerformed

    private void editarContrasenaCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarContrasenaCBActionPerformed
        if(editarContrasenaCB.isSelected()){
            contrasenaT.setEnabled(true);
            rContrasenaT.setEnabled(true);
        }
        else{
           contrasenaT.setEnabled(false);
            rContrasenaT.setEnabled(false); 
        }
        
    }//GEN-LAST:event_editarContrasenaCBActionPerformed

    private void tesoreriaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tesoreriaBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tesoreriaBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox activoCB;
    private javax.swing.JTextField apellidosT;
    private javax.swing.JRadioButton cobranzaB;
    private javax.swing.JPasswordField contrasenaT;
    private javax.swing.JRadioButton cuentasB;
    private javax.swing.JCheckBox editarContrasenaCB;
    private javax.swing.JTextField emailT;
    private javax.swing.JRadioButton gastosB;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombresT;
    private javax.swing.JLabel permisosL;
    private javax.swing.JRadioButton piedraB;
    private javax.swing.JPasswordField rContrasenaT;
    private javax.swing.JRadioButton reportesB;
    private javax.swing.JRadioButton tesoreriaB;
    private javax.swing.JTextField usuarioT;
    private javax.swing.JRadioButton ventasB;
    // End of variables declaration//GEN-END:variables
}
