/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gravicor;

import javafx.scene.control.RadioButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.filechooser.FileSystemView;

/**
 *
 * @author Gravicor
 */
public class GenerarReportes extends javax.swing.JFrame {

    //array que guarda los radio buttons
    private JRadioButton[] radioButtons = new JRadioButton[7];
    
    public GenerarReportes() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("Generar reportes");
        generarradiolist();
        
    }
    
    //metodo que declara el array de los radio buttons
    private void generarradiolist(){
        this.radioButtons[0] = this.radioCamionesB;
        this.radioButtons[1] = this.radioClientesB; 
        this.radioButtons[2] = this.radioFacturasB; 
        this.radioButtons[3] = this.radioGastosGeneralesB;
        this.radioButtons[4] = this.radioVentasB;
        this.radioButtons[5] = this.radioVentasFantasmaB;
        this.radioButtons[6] = this.radioViajesB;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        pathTF = new javax.swing.JTextField();
        radioCamionesB = new javax.swing.JRadioButton();
        radioClientesB = new javax.swing.JRadioButton();
        radioFacturasB = new javax.swing.JRadioButton();
        radioGastosGeneralesB = new javax.swing.JRadioButton();
        radioVentasB = new javax.swing.JRadioButton();
        radioVentasFantasmaB = new javax.swing.JRadioButton();
        radioViajesB = new javax.swing.JRadioButton();
        CamionesActivosCB = new javax.swing.JCheckBox();
        camionesInactivosCB = new javax.swing.JCheckBox();
        generarReportesB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(249, 255, 255));

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Ubicación de archivo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        pathTF.setEditable(false);

        radioCamionesB.setText("Reporte de camiones");
        radioCamionesB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCamionesBActionPerformed(evt);
            }
        });

        radioClientesB.setText("Reporte de clientes");
        radioClientesB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioClientesBActionPerformed(evt);
            }
        });

        radioFacturasB.setText("Reporte de facturas");
        radioFacturasB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioFacturasBActionPerformed(evt);
            }
        });

        radioGastosGeneralesB.setText("Reporte de gastos generales");
        radioGastosGeneralesB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioGastosGeneralesBActionPerformed(evt);
            }
        });

        radioVentasB.setText("Reporte de ventas");
        radioVentasB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioVentasBActionPerformed(evt);
            }
        });

        radioVentasFantasmaB.setText("Reporte de ventas fantasmas");
        radioVentasFantasmaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioVentasFantasmaBActionPerformed(evt);
            }
        });

        radioViajesB.setText("Reporte de viajes de piedra en greña");
        radioViajesB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioViajesBActionPerformed(evt);
            }
        });

        CamionesActivosCB.setText("Camiones Activos");

        camionesInactivosCB.setText("Camiones Inactivos");

        generarReportesB.setText("Generar Reportes");
        generarReportesB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarReportesBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jButton1)
                .addGap(97, 97, 97)
                .addComponent(pathTF, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(136, 136, 136))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(radioCamionesB)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(radioViajesB)
                                    .addComponent(radioVentasFantasmaB, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radioVentasB, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radioGastosGeneralesB, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radioClientesB, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CamionesActivosCB)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(radioFacturasB)
                                .addGap(86, 86, 86)))
                        .addGap(56, 56, 56)
                        .addComponent(camionesInactivosCB))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(356, 356, 356)
                        .addComponent(generarReportesB)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(pathTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addComponent(radioCamionesB)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CamionesActivosCB)
                    .addComponent(camionesInactivosCB))
                .addGap(20, 20, 20)
                .addComponent(radioClientesB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(radioFacturasB)
                .addGap(67, 67, 67)
                .addComponent(radioGastosGeneralesB)
                .addGap(85, 85, 85)
                .addComponent(radioVentasB)
                .addGap(54, 54, 54)
                .addComponent(radioVentasFantasmaB)
                .addGap(61, 61, 61)
                .addComponent(radioViajesB)
                .addGap(48, 48, 48)
                .addComponent(generarReportesB)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MenuPrincipal menu= new MenuPrincipal();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JFileChooser j = new JFileChooser(FileSystemView.getFileSystemView()); 
        j.showSaveDialog(null); 
        try{
            pathTF.setText(j.getSelectedFile().getAbsolutePath() + ".csv");
        }
        catch(Exception e){
            
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void radioCamionesBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCamionesBActionPerformed
        // TODO add your handling code here:
        limpiarOpciones();
        this.radioCamionesB.setSelected(true);
    }//GEN-LAST:event_radioCamionesBActionPerformed

    private void radioClientesBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioClientesBActionPerformed
        // TODO add your handling code here:
        limpiarOpciones();
        this.radioClientesB.setSelected(true);
    }//GEN-LAST:event_radioClientesBActionPerformed

    private void radioFacturasBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioFacturasBActionPerformed
        // TODO add your handling code here:
        limpiarOpciones();
        this.radioFacturasB.setSelected(true);
    }//GEN-LAST:event_radioFacturasBActionPerformed

    private void radioGastosGeneralesBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioGastosGeneralesBActionPerformed
        // TODO add your handling code here:
        limpiarOpciones();
        this.radioGastosGeneralesB.setSelected(true);
    }//GEN-LAST:event_radioGastosGeneralesBActionPerformed

    private void radioVentasBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioVentasBActionPerformed
        // TODO add your handling code here:
        limpiarOpciones();
        this.radioVentasB.setSelected(true);
    }//GEN-LAST:event_radioVentasBActionPerformed

    private void radioVentasFantasmaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioVentasFantasmaBActionPerformed
        // TODO add your handling code here:
        limpiarOpciones();
        this.radioVentasFantasmaB.setSelected(true);
    }//GEN-LAST:event_radioVentasFantasmaBActionPerformed

    private void radioViajesBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioViajesBActionPerformed
        // TODO add your handling code here:
        limpiarOpciones();
        this.radioViajesB.setSelected(true);
    }//GEN-LAST:event_radioViajesBActionPerformed

    //metodo que regresa el radiobutton que esta seleccionado
    private int radioButtonSeleccionado(){
        
        for(int i = 0; i < this.radioButtons.length; i++){
            if(this.radioButtons[i].isSelected()){
                return i;
            }
        }
        
        return -1;
    }
    
   //Metodo que genera los reportes
    private void generarReportesBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarReportesBActionPerformed
        // TODO add your handling code here:
        try{
            int radioButtonSeleccionado = radioButtonSeleccionado();
            switch (radioButtonSeleccionado){
                case -1: //no hay ninguna opcion seleccionada
                    throw new NoTypeRequiredException("Por favor selecciona una opcion para generar un reporte");
                case 0:// reporte de camiones
                    
            }
        }
        catch(NoTypeRequiredException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error procesar la solicitud", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_generarReportesBActionPerformed

    //metodo que limpia todos los radio buttons
    private void limpiarOpciones(){
        for(JRadioButton button : this.radioButtons){
            button.setSelected(false);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenerarReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenerarReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenerarReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenerarReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GenerarReportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CamionesActivosCB;
    private javax.swing.JCheckBox camionesInactivosCB;
    private javax.swing.JButton generarReportesB;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField pathTF;
    private javax.swing.JRadioButton radioCamionesB;
    private javax.swing.JRadioButton radioClientesB;
    private javax.swing.JRadioButton radioFacturasB;
    private javax.swing.JRadioButton radioGastosGeneralesB;
    private javax.swing.JRadioButton radioVentasB;
    private javax.swing.JRadioButton radioVentasFantasmaB;
    private javax.swing.JRadioButton radioViajesB;
    // End of variables declaration//GEN-END:variables
}
