use gravicor

select convert(varchar, viaje.FECHA, 106) as Fecha,  CONVERT(VARCHAR, VIAJE.HORA, 108) as Hora from viaje




INSERT INTO VIAJE (IDUSUARIO,IDCAMION,FECHA,HORA,ESACTIVO)
VALUES (1,1, GETDATE(), GETdATE(), 1); 

SELECT convert(varchar, getdate(), 106)

Select CONVERT(VARCHAR, VIAJE.HORA, 108) as Hora from viaje where VIAJE.IDCAMION = 1

SELECT USUARIO.IDUSUARIO FROM USUARIO WHERE USUARIO.USERNAME = 'luisdaniel'

SELECT CONVERT(VARCHAR, GETDATE(), 108) as HoraActual

Select CONVERT(VARCHAR, VIAJE.HORA, 108) as Hora from viaje where VIAJE.IDCAMION = 1 and viaje.FECHA = convert(varchar, getDate(), 106)

Select  convert(varchar, viaje.FECHA, 106) as Fecha,  CONVERT(VARCHAR, VIAJE.HORA, 108) as Hora from VIAJE WHERE VIAJE.IDCAMION = 2 and VIAJE.ESACTIVO = 1

SELECT CAMION.IDCAMION,TIPOCAMION.DESCRIPCION,TIPOCAMION.CAPACIDAD, COUNT(*) AS CONTEO, SUM(TIPOCAMION.TONELADAS) AS SUBTOTALTONELADAS
FROM CAMION, VIAJE, TIPOCAMION
WHERE CAMION.IDCAMION = VIAJE.IDCAMION AND CAMION.IDTIPOCAMION = TIPOCAMION.IDTIPOCAMION AND convert(varchar, VIAJE.FECHA, 106) = convert(varchar, getDate(), 106)
GROUP BY VIAJE.IDCAMION, CAMION.IDCAMION, TIPOCAMION.DESCRIPCION, TIPOCAMION.CAPACIDAD

SELECT SUM(TIPOCAMION.CAPACIDAD) AS TOTALMC, SUM(TIPOCAMION.TONELADAS) AS TOTALTONELADAS 
FROM VIAJE, CAMION, TIPOCAMION
WHERE CAMION.IDCAMION = VIAJE.IDCAMION  AND convert(varchar, VIAJE.FECHA, 106) = convert(varchar, getDate(), 106) AND CAMION.IDTIPOCAMION = TIPOCAMION.IDTIPOCAMION

SELECT ACTIVO.DESCRIPCION
FROM CAMION, ACTIVO
WHERE CAMION.ACTIVO = ACTIVO.IDACTIVO AND CAMION.IDCAMION = 13

SELECT convert(varchar, getdate(), 105)
